import turtle

screen = turtle.getscreen()
screen.title("Khipu Simulator")
screen.bgcolor("black")

def drawCredits(x,y):
	turtle.clearscreen()
	screen.bgcolor("black")
	turtle.hideturtle()
	turtle.penup()
	turtle.speed(0)
	turtle.pen(pencolor="white")
	turtle.sety(200)
	turtle.write("khipu simulator", True, align="center", font=("Panibo", 100, "normal"))
	turtle.setx(0)
	turtle.sety(100)
	turtle.write("developed by isabela de almeida", True, align="center", font=("Panibo", 30, "normal"))
	turtle.setx(0)
	turtle.sety(0)
	turtle.write("references", True, align="center", font=("Panibo", 30, "normal"))
	turtle.setx(0)
	turtle.sety(-45)
	turtle.write("Inka History in Knots by Gary Urthon", True, align="center", font=("Panibo", 30, "normal"))
	turtle.setx(0)
	turtle.sety(-90)
	turtle.write("Writing with twisted cords by Sabine Hyland", True, align="center", font=("Panibo", 30, "normal"))
	turtle.setx(0)
	turtle.sety(-135)
	turtle.write("The Khipu Field Guide by Ashok Khosla", True, align="center", font=("Panibo", 30, "normal"))
	turtle.setx(0)
	turtle.sety(-180)
	turtle.write("coding with knots by Dave Griffiths", True, align="center", font=("Panibo", 30, "normal"))
	turtle.setx(0)
	turtle.sety(-280)
	turtle.write("Special thanks to professor Eduardo Neves for the classes", True, align="center", font=("Panibo", 30, "normal"))
	turtle.setx(0)
	turtle.sety(-325)
	turtle.write("to Rafael Lopes his assistant and ", True, align="center", font=("Panibo", 30, "normal"))
	turtle.setx(0)
	turtle.sety(-370)
	turtle.write("to Victor Feitosa for the help with the debbuging and support.", True, align="center", font=("Panibo", 30, "normal"))
