import turtle

turtle.register_shape("src/khipu-sewing.gif")

def drawChecksums(x, y):
	turtle.clearscreen()
	screen.bgcolor("black")
	## configure pen
	turtle.pendown()
	hand = turtle.Turtle()
	hand.pen(pencolor="white", pensize=2, speed=10)
	hand.shape("src/khipu-sewing.gif")	
	hand.circle(200,-90)
	hand.circle(200,180)
	hand.circle(200,-145)
	hand.pen(pencolor="brown", pensize=2, speed=1)
	hand.seth(180+45)
	hand.fd(25)
	hand.color("brown")
	hand.begin_fill()
	hand.circle(4)
	hand.seth(180+45)
	hand.fd(4)
	hand.seth(180+45)
	hand.fd(4)
	hand.circle(4)
	hand.end_fill()
	hand.fd(50)
	hand.penup()
	hand.seth(0)
	hand.goto(0,0)
	hand.color("white")
	hand.pendown()
	hand.seth(270)
	hand.fd(25)
	hand.begin_fill()
	hand.circle(4)
	hand.seth(270)
	hand.fd(4)
	hand.seth(270)
	hand.fd(4)
	hand.circle(4)
	hand.end_fill()
	hand.fd(50)

# set environment
screen = turtle.getscreen()
screen.title("Khipu Simulator")
screen.setup (width=.9, height=.95)
screen.bgcolor("black")

#write title
turtle.hideturtle()
turtle.penup()
turtle.speed(0)
turtle.pen(pencolor="white")
turtle.sety(200)
turtle.write("Khipu Simulator", True, align="center", font=("Panibo", 100, "normal"))

#configure buttons
button_1 = turtle.Turtle()
button_1.penup()
button_1.shapesize(4, 12)
button_1.sety(60)
button_1.shape("square")
button_1.speed(0)
button_1_pos = (0.00,60.00)
button_1.onclick(drawChecksums)

button_2 = turtle.Turtle()
button_2.shapesize(4, 12)
button_2.sety(-40)
button_2.shape("square")
button_2.speed(0)
button_2_pos = button_2.pos()

button_3 = turtle.Turtle()
button_3.shapesize(4, 12)
button_3.sety(-140)
button_3.shape("square")
button_3.speed(0)
button_3_pos = button_3.pos()

button_4 = turtle.Turtle()
button_4.shapesize(4, 12)
button_4.sety(-240)
button_4.shape("square")
button_4.speed(0)
button_4_pos = button_4.pos()

button_1.pen(pencolor="white", pensize=50)
button_1.fillcolor("white")
button_2.pen(pencolor="white", pensize=50)
button_2.fillcolor("white")
button_3.pen(pencolor="white", pensize=50)
button_3.fillcolor("white")
button_4.pen(pencolor="white", pensize=50)
button_4.fillcolor("white")

button_1_caption = turtle.Turtle()
button_1_caption.hideturtle()
button_1_caption.penup()
button_1_caption.speed(0)
button_1_caption.pen(pencolor="black")
button_1_caption.sety(45)
button_1_caption.write("check sums", True, align="center", font=("Panibo", 20, "normal"))

button_2_caption = turtle.Turtle()
button_2_caption.hideturtle()
button_2_caption.penup()
button_2_caption.speed(0)
button_2_caption.pen(pencolor="black")
button_2_caption.sety(-55)
button_2_caption.write("census", True, align="center", font=("Panibo", 20, "normal"))

button_3_caption = turtle.Turtle()
button_3_caption.hideturtle()
button_3_caption.penup()
button_3_caption.speed(0)
button_3_caption.pen(pencolor="black")
button_3_caption.sety(-155)
button_3_caption.write("storage", True, align="center", font=("Panibo", 20, "normal"))

button_4_caption = turtle.Turtle()
button_4_caption.hideturtle()
button_4_caption.penup()
button_4_caption.speed(0)
button_4_caption.pen(pencolor="black")
button_4_caption.sety(-255)
button_4_caption.write("credits", True, align="center", font=("Panibo", 20, "normal"))

turtle.getscreen()._root.mainloop()
